name: Test

on:
  - push

jobs:
  test:
    runs-on: self-hosted
    container:
      image: node:10
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: npx ng lint
