name: Test

on:
  - push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Install node
        run: |
          curl -L https://deb.nodesource.com/setup_10.x | sh -
          apt install nodejs
          npm i -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: npx ng lint
